### ISSUE TITLE
seed値が設定できるようにしてほしい

### ISSUE THREAD

**Issue by soukouki** [s-osa/random_bell#4]

**Comment by s-osa** [comment]
@soukouki 
実際にどういうケースで使いたいのか教えていただけますか？
（なんとなくわかりますが一応）

**Comment by soukouki** [comment]
迅速な対応ありがとうございます。

> 実際にどういうケースで使いたいのか

ゲームの乱数等で使う予定です。

**Comment by s-osa** [comment]
再現性のある擬似乱数列が欲しいから、seed を指定したいということですよね？

**Comment by s-osa** [comment]
#5 を含めたバージョンを v0.2.0 としてリリースしました。
https://rubygems.org/gems/random_bell/versions/0.2.0
